name: Python Tests 

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13 

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        uses: actions/checkout@v4
        run: python -m pip install -r requirements.txt 

      - name: Run Tests with Tox
        run: tox
