name: Python Tests 

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python

        with:
          tox_env: py312

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install 

      - name: Run Tests with Tox
        run: poetry run tox
