name: Python Tests 

on:
  push:
    branches: [ main ]

jobs:
  if: false
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.13
            3.12 

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install 

      - name: Run Tests with Tox
        run: poetry run tox
