name: Python Tests 

on:
  push:
    branches: [ dev ]

jobs:
  tox_test:
    name: Tox test

    steps:
    - uses: actions/checkout@v2
    - name: Run tox tests
      id: test

      uses: fedora-python/tox-github-action@main
      with:
        tox_env: py313
        workdir: "ciwithfedora/"

    runs-on: ubuntu-latest

