name: Python Tests 

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: fedora-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13 

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install 
        working-directory: .

      - name: Run Tests with Tox
        run: tox
