name: Python Tests 

on:
  push:
    branches: [ dev ]

jobs:
  test:
    steps:
      - uses: actions/checkout@v2
      - name: Run tox tests

      - uses: fedora-python/tox-github-action@main
        with:
          tox_env: py313

      runs-on: ubuntu-latest

